[package]

name = "bodyparser"
version = "0.0.4"
license = "MIT"
description = "Body parsing middleware for Iron."
repository = "https://github.com/iron/body-parser"
documentation = "http://ironframework.io/doc/bodyparser/index.html"
authors = ["Patrick Tran <patrick.tran06@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]

[dependencies]
iron = "*"
rustc-serialize = "*"
plugin = "*"
persistent = "*"
